# Week2授業前課題3

## 【課題1】内積を手計算しよう
以下のような行列A,Bを考えます。  
$$
    A =
    \begin{bmatrix}
    -1 & 2 & 3 \\
    4 & -5 &  6 \\
    7 & 8 &  -9 \\
    \end{bmatrix},\quad 
     B =
    \begin{bmatrix}
    0 & 2 & 1 \\
    0 & 2 &  -8 \\
    2 & 9 &  -1 \\
    \end{bmatrix}
$$

行列の内積A*Bを手計算で解きなさい。

$
\begin{align}
A\cdot B &= 
    \begin{bmatrix}
        -1\cdot 0 + 2\cdot 0 + 3\cdot 2 & -1\cdot 2 + 2\cdot 2 + 3\cdot 9 & -1\cdot 1 + 2\cdot (-8) + 3\cdot (-1) \\
        4\cdot 0 + (-5)\cdot 0 + 6\cdot 2 & 4\cdot 2 + (-5)\cdot 2 + 6\cdot 9 &  4\cdot 1 + (-5)\cdot (-8) + 6\cdot (-1) \\
        7\cdot 0 + 8\cdot 0 + (-9)\cdot 2 & 7\cdot 2 + 8\cdot 2 + (-9)\cdot 9 &  7\cdot 1 + 8\cdot (-8) + (-9)\cdot (-1) \\
    \end{bmatrix} \\
    &=
    \begin{bmatrix}
        6 & 29 & -20 \\
        12 & 52 & -38 \\
        -18 & -51 & -48 \\
    \end{bmatrix}
\end{align}
$

## 【課題2】1次元配列の内積をfor文で計算しよう
これ以降の課題はNumPyを使って解いてください。

【課題1】では手計算してもらいました。一つ一つの演算はさほど難しくありませんが、演算数は多くかなり面倒くさかったと思います。

この演算をpythonを使って実装するとどうなるのでしょうか？

手計算する際には、まず行列Aの1行目と行列Bの1列目に注目したと思います。そして、

- 行列Aの(0,0)の要素と行列Bの(0,0)の要素を掛け合わせる
- 行列Aの(0,1)の要素と行列Bの(1,0)の要素を掛け合わせる
- 行列Aの(0,2)の要素と行列Bの(2,0)の要素を掛け合わせる
- それらの値を全て足し合わせる
というフローを得て、ようやく一つ目の要素が求まるわけです。

次の要素を計算するには、行列のindexを増やし、上の過程を再度繰り返して行けば良いわけです。下図のようなイメージですね。


まずは、ご自身で配列のindexを指定し、

- 行列Aの(0,0)の要素と行列Bの(0,1)の要素を掛け合わせる
- 行列Aの(0,1)の要素と行列Bの(1,1)の要素を掛け合わせる
- 行列Aの(0,2)の要素と行列Bの(2,1)の要素を掛け合わせる
- それらの値を全て足し合わせる  
のフローをfor文を使って計算してください。



In [1]:
import numpy as np

#行列の定義
A = np.array([
    [-1, 2, 3],
    [4, -5, 6],
    [7, 8, -9]
])

B = np.array([
    [0, 2, 1],
    [0, 2, -8],
    [2, 9, -1]
])

# A*Bの(0,0)の定義
ab11 = 0
# Aの１行目とBの１列目の乗算
for i in range(3):
    ab11 += A[0][i] * B[i][0]

# A*Bの(0,0)出力
print(ab11)

6


## 【課題3】多次元配列の内積をfor文で計算しよう
【課題2】ではA*Bの(0,0)だけ計算するコードを実装してもらいましたが、全要素を求めるにはどうしたら良いでしょうか？

行列A*Bの(0,1)を求めるには

行列Aのインデックスは固定（0行目を選択したまま）で、行列Bのインデックスを0列目から1列目に指定しなおせば良いわけです。理解できない方は、手計算でのフローを思い出してください！

- 行列Aの(0,0)の要素と行列Bの(0,1)の要素を掛け合わせる
- 行列Aの(0,1)の要素と行列Bの(1,1)の要素を掛け合わせる
- 行列Aの(0,2)の要素と行列Bの(2,1)の要素を掛け合わせる
- 1、2、3で求めた値を足し合わせる
とすればA*Bの(0,1)の要素が求まります。

このように同じ計算を順次インデックスを増やして行けば、全要素の計算ができます。

計算の処理自体は全て同じなので、指定する要素の場所をなんとか効率よくできないかというところで登場するのが、for文です。

説明はここまでになります。

for文を使って行列A、Bの積を計算しましょう！【課題2】では(0,0)のみ計算していただきましたが、全て計算してください。


> indexの移行は行方向と列方向があるので、【課題2】で実装していただいたコードに加えて、さらに2回for文が必要になります。


In [95]:
import numpy as np

#行列の定義
A = np.array([
    [-1, 2, 3],
    [4, -5, 6],
    [7, 8, -9]
])

B = np.array([
    [0, 2, 1],
    [0, 2, -8],
    [2, 9, -1]
])

# ABを格納する多次元リストを初期化
AB = np.empty((0,3), int)

#Aの行数分の計算
for k in range(3):
    #ABのi行目を格納するリスト
    ab_i = np.array([])
    #Bの列数分の計算
    for j in range(3):
        #ABの(i, j)を初期化
        ab_ij = 0
        #a_ij 、b_ijの乗算
        for i in range(3):
            ab_ij += A[k][i] * B[i][j]
        #ABの(i, j)をABのi行目に格納する
        ab_i = np.append(ab_i, ab_ij)
    #ABのi行目をABリストに格納する
    AB = np.append(AB, np.array([ab_i]), axis=0)

#　計算結果の出力
print(AB)

[[  6.  29. -20.]
 [ 12.  52.  38.]
 [-18. -51. -48.]]


## 【課題4】内積をnp.dotで計算しよう
【課題3】ではfor文を使うことで、内積を計算していただきましたが、行列の内積演算の度にこのようにfor文の処理を何回も実装しなくてもはならないのでしょうか？

当然そんなことはなく、実はみなさんがやっていただいた処理はnumpyのメソッドですでに用意されています。

np.dot(A,B)と計算すると、【課題3】で計算していただいたことが一瞬でできます。

np.dot(A,B)を計算して、【課題3】と同じになることを試してください。





In [99]:
import numpy as np

A = np.array([
    [-1, 2, 3],
    [4, -5, 6],
    [7, 8, -9]
])

B = np.array([
    [0, 2, 1],
    [0, 2, -8],
    [2, 9, -1]
])

#　np.dotで計算
print(np.dot(A, B))

[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


## 【課題5】内積ができないときはどうするか
以下のような例を考えます。

$$
    A =
    \begin{bmatrix}
    -1 & 2 & 3 \\
    4 & -5 &  6 \\
    \end{bmatrix},\quad 
     B =
    \begin{bmatrix}
    -9 & 8 & 7 \\
    6 & -5 &  4 \\
    \end{bmatrix}
$$

行列A*Bを計算しようとすると、エラーが出て計算できません。なぜエラーが出るのか理由を記載してください。

そして、行列A、Bのどちらかにある操作をするとエラーが出ずに計算できます。

自分である操作を施し、内積を計算してください。

### エラーが出る理由
行列の積の定義として、$A$の列数と$B$の行数が一致しているときのみ積$AB$は定義される。  
今回、$A$の列数は3、$B$の行数は2であるため、エラーが出て計算ができない。  
積の計算を行うためには、AまたはBの行列に対して転置を行うことが必要。

In [103]:
import numpy as np

# 【課題5】のA,Bの行列定義
A = np.array([
    [-1, 2, 3],
    [4, -5, 6]
])

B = np.array([
    [-9, 8, 7],
    [6, -5, 4]
])

# Aの転置を行い、転置AとBの積を計算する
print(np.dot(A.T, B))


[[ 33 -28   9]
 [-48  41  -6]
 [  9  -6  45]]
